# Generated by Django 6.0.3 on 2026-04-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã NL')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nguyên liệu')),
                ('unit', models.CharField(max_length=50, verbose_name='ĐVT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RawMaterial',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá so sánh'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá vốn'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú sản xuất'),
        ),
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Định lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='ĐVT')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='api.product', verbose_name='Sản phẩm')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='api.rawmaterial', verbose_name='Nguyên liệu')),
            ],
            options={
                'verbose_name': 'ProductBOM',
                'unique_together': {('product', 'raw_material')},
            },
        ),
    ]
