# Generated by Django 6.0.3 on 2026-04-26 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_material_notes_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ten nha cung cap')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='So dien thoai')),
                ('address', models.TextField(blank=True, verbose_name='Dia chi')),
                ('status', models.CharField(choices=[('active', 'Dang hoat dong'), ('inactive', 'Tam ngung')], default='active', max_length=20, verbose_name='Trang thai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product'},
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma phieu')),
                ('total_value', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Tong gia tri')),
                ('status', models.CharField(choices=[('draft', 'Luu nhap'), ('waiting', 'Cho nhan'), ('received', 'Da nhan'), ('cancelled', 'Da huy')], default='draft', max_length=20, verbose_name='Trang thai')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.supplier', verbose_name='Nha cung cap')),
            ],
            options={
                'verbose_name': 'PurchaseOrder',
                'ordering': ['-id'],
            },
        ),
    ]
