# Generated by Django 6.0.3 on 2026-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_supplier_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma dia diem')),
                ('name', models.CharField(max_length=200, verbose_name='Ten dia diem')),
                ('address', models.TextField(blank=True, verbose_name='Dia chi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='So dien thoai')),
                ('status', models.CharField(choices=[('active', 'Dang hoat dong'), ('inactive', 'Tam ngung')], default='active', max_length=20, verbose_name='Trang thai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ['-id'],
            },
        ),
    ]
