# Generated by Django 6.0.3 on 2026-04-29 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='allow_delivery',
            field=models.BooleanField(default=False, verbose_name='Cho phep giao hang'),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quan huyen'),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_types',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loai dia diem'),
        ),
        migrations.AddField(
            model_name='location',
            name='manage_btp',
            field=models.BooleanField(default=False, verbose_name='Quan ly BTP'),
        ),
        migrations.AddField(
            model_name='location',
            name='manage_nvl',
            field=models.BooleanField(default=False, verbose_name='Quan ly NVL'),
        ),
        migrations.AddField(
            model_name='location',
            name='manage_thanh_pham',
            field=models.BooleanField(default=False, verbose_name='Quan ly thanh pham'),
        ),
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL, verbose_name='Nhan vien quan ly'),
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tinh thanh pho'),
        ),
        migrations.AddField(
            model_name='location',
            name='ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phuong xa'),
        ),
    ]
