# Generated by Django 6.0.3 on 2026-04-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_location_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma don vi')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ten don vi van chuyen')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='So dien thoai')),
                ('status', models.CharField(choices=[('active', 'Dang hoat dong'), ('inactive', 'Tam ngung')], default='active', max_length=20, verbose_name='Trang thai')),
                ('created_by_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi tao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ShippingUnit',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingUnitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi thuc hien')),
                ('action', models.CharField(max_length=300, verbose_name='Hanh dong')),
                ('shipping_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.shippingunit', verbose_name='Don vi van chuyen')),
            ],
            options={
                'verbose_name': 'ShippingUnitHistory',
                'ordering': ['-timestamp'],
            },
        ),
    ]
