# Generated by Django 6.0.3 on 2026-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_shipping_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingunit',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dia chi'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tinh/Thanh pho'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quan/Huyen'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chu'),
        ),
        migrations.AddField(
            model_name='shippingunit',
            name='ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phuong/Xa'),
        ),
        migrations.AlterField(
            model_name='shippingunit',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ma doi tac'),
        ),
        migrations.AlterField(
            model_name='shippingunit',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ten doi tac'),
        ),
        migrations.AlterField(
            model_name='shippingunit',
            name='status',
            field=models.CharField(choices=[('active', 'Dang hoat dong'), ('inactive', 'Ngung hoat dong')], default='active', max_length=20, verbose_name='Trang thai'),
        ),
    ]
