# Generated by Django 6.0.3 on 2026-04-30 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_shippingunit_address_shippingunit_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma nhan vien')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ho va ten')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='So dien thoai')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Vai tro')),
                ('shift', models.CharField(blank=True, max_length=100, verbose_name='Ca lam viec')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngay vao lam')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngay sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nu'), ('other', 'Khac')], max_length=10, verbose_name='Gioi tinh')),
                ('id_number', models.CharField(blank=True, max_length=30, verbose_name='So CMND/CCCD')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dia chi')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Tinh thanh pho')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quan huyen')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phuong xa')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/avatars/')),
                ('contract_image', models.ImageField(blank=True, null=True, upload_to='employees/contracts/')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('salary_base', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Luong co ban')),
                ('salary_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phu cap')),
                ('status', models.CharField(choices=[('working', 'Dang lam viec'), ('stopped', 'Ngung lam viec')], default='working', max_length=20, verbose_name='Trang thai')),
                ('created_by_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi tao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.location', verbose_name='Khu vuc lam viec')),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi thuc hien')),
                ('action', models.CharField(max_length=300, verbose_name='Hanh dong')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.employee', verbose_name='Nhan vien')),
            ],
            options={
                'verbose_name': 'EmployeeHistory',
                'ordering': ['-timestamp'],
            },
        ),
    ]
