# Generated by Django 6.0.3 on 2026-04-30 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã chính sách')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chính sách')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BenefitsPolicy',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã tỉnh')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tỉnh')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Tên tiếng Anh')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('code_name', models.CharField(blank=True, max_length=100, verbose_name='Tên không dấu')),
            ],
            options={
                'verbose_name': 'Province',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã loại lương')),
                ('name', models.CharField(max_length=200, verbose_name='Tên loại lương')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SalaryType',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='district_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ma quan huyen'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_salary_info',
            field=models.BooleanField(default=False, verbose_name='Co thong tin luong'),
        ),
        migrations.AddField(
            model_name='employee',
            name='province_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ma tinh thanh pho'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Muc luong'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ward_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ma phuong xa'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ten truong'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Gia tri moi'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Gia tri cu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='employees', to='api.benefitspolicy', verbose_name='Phuc loi'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã quận/huyện')),
                ('name', models.CharField(max_length=100, verbose_name='Tên quận/huyện')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Tên tiếng Anh')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('code_name', models.CharField(blank=True, max_length=100, verbose_name='Tên không dấu')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.province', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'District',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.salarytype', verbose_name='Loai luong'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã phường/xã')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phường/xã')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Tên tiếng Anh')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('code_name', models.CharField(blank=True, max_length=100, verbose_name='Tên không dấu')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='api.district', verbose_name='Quận/Huyện')),
            ],
            options={
                'verbose_name': 'Ward',
                'ordering': ['name'],
            },
        ),
    ]
