# Generated by Django 6.0.3 on 2026-04-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_benefitspolicy_province_salarytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma ca lam viec')),
                ('name', models.CharField(max_length=200, verbose_name='Ten ca lam viec')),
                ('start_time', models.TimeField(verbose_name='Gio bat dau')),
                ('end_time', models.TimeField(verbose_name='Gio ket thuc')),
                ('status', models.CharField(choices=[('active', 'Dang hoat dong'), ('inactive', 'Ngung hoat dong')], default='active', max_length=20, verbose_name='Trang thai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WorkShift',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkShiftBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField(verbose_name='Gio bat dau nghi')),
                ('break_end', models.TimeField(verbose_name='Gio ket thuc nghi')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='api.workshift', verbose_name='Ca lam viec')),
            ],
            options={
                'verbose_name': 'WorkShiftBreak',
                'ordering': ['break_start'],
            },
        ),
        migrations.CreateModel(
            name='WorkShiftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi thuc hien')),
                ('action', models.CharField(max_length=300, verbose_name='Hanh dong')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.workshift', verbose_name='Ca lam viec')),
            ],
            options={
                'verbose_name': 'WorkShiftHistory',
                'ordering': ['-timestamp'],
            },
        ),
    ]
