# Generated by Django 6.0.3 on 2026-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_benefitspolicy_province_salarytype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhóm sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm ngưng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'ordering': ['-id'],
            },
        ),
    ]
