# Generated by Django 6.0.3 on 2026-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nguoi tao'),
        ),
        migrations.AddField(
            model_name='workshifthistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ten truong'),
        ),
        migrations.AddField(
            model_name='workshifthistory',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Gia tri moi'),
        ),
        migrations.AddField(
            model_name='workshifthistory',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Gia tri cu'),
        ),
    ]
