# Generated by Django 6.0.3 on 2026-04-30 12:20

from django.db import migrations, models


def seed_material_groups(apps, schema_editor):
    Material = apps.get_model('api', 'Material')
    MaterialGroup = apps.get_model('api', 'MaterialGroup')

    names = (
        Material.objects.exclude(group__isnull=True)
        .exclude(group__exact='')
        .order_by('group')
        .values_list('group', flat=True)
        .distinct()
    )

    for index, name in enumerate(names, start=1):
        MaterialGroup.objects.get_or_create(
            name=name,
            defaults={
                'code': f'MNH{index:03d}',
                'description': '',
                'status': 'active',
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhóm nguyên vật liệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Tạm ngưng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Group',
                'verbose_name_plural': 'Material Groups',
                'ordering': ['-id'],
            },
        ),
        migrations.RunPython(seed_material_groups, noop_reverse),
    ]
