# Generated by Django 6.0.3 on 2026-04-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_workshift_created_by_name_and_more'),
    ]

    operations = [
    ]
