# Generated by Django 6.0.3 on 2026-04-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bonus_bonushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-bonus_date', '-id'], 'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='bonushistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'BonusHistory', 'verbose_name_plural': 'BonusHistories'},
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='bonus_type',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='recipient_type',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Số tiền thưởng'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='api.employee', verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thưởng'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã thưởng'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.CharField(max_length=500, verbose_name='Lý do thưởng'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngưng hoạt động')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='action',
            field=models.CharField(max_length=300, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='actor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.bonus', verbose_name='Thưởng'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên trường'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Giá trị mới'),
        ),
        migrations.AlterField(
            model_name='bonushistory',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Giá trị cũ'),
        ),
    ]
