# Generated by Django 6.0.3 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_bonus_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='employee',
        ),
        migrations.AddField(
            model_name='bonus',
            name='amount_per_person',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Mức thưởng từng'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(choices=[('direct', 'Thưởng trực tiếp'), ('salary', 'Thưởng vào lương')], default='direct', max_length=20, verbose_name='Hình thức thưởng'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='employee_count',
            field=models.IntegerField(default=0, verbose_name='Số lượng NV được thưởng'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='bonuses', to='api.employee', verbose_name='Nhân viên được thưởng'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'Tất cả nhân viên'), ('selected', 'Tùy chọn')], default='selected', max_length=20, verbose_name='Loại người nhận'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng tiền thưởng'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
