# Generated by Django 6.0.3 on 2026-05-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_update_bonus_model_for_multiple_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-id'], 'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonuses'},
        ),
    ]
