# Generated by Django 6.0.3 on 2026-05-01 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_update_bonus_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã phúc lợi')),
                ('name', models.CharField(max_length=500, verbose_name='Tên chính sách phúc lợi')),
                ('benefit_type', models.CharField(choices=[('phu_cap', 'Phụ cấp'), ('chinh_sach', 'Chính sách'), ('van_hoa', 'Văn hoá'), ('khac', 'Khác')], default='phu_cap', max_length=30, verbose_name='Loại phúc lợi')),
                ('scope', models.CharField(choices=[('toan_cong_ty', 'Toàn công ty'), ('theo_vai_tro', 'Theo vai trò'), ('ca_nhan', 'Cá nhân')], default='toan_cong_ty', max_length=30, verbose_name='Phạm vi áp dụng')),
                ('cycle', models.CharField(choices=[('hang_ngay', 'Hàng ngày'), ('hang_thang', 'Hàng tháng'), ('hang_quy', 'Hàng quý'), ('hang_nam', 'Hàng năm'), ('ngay_le_tet', 'Ngày lễ, tết'), ('su_kien', 'Sự kiện')], default='hang_thang', max_length=30, verbose_name='Chu kỳ áp dụng')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Hiệu lực từ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến')),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá trị phúc lợi')),
                ('value_unit', models.CharField(choices=[('dong', 'đồng'), ('phan_tram', '%')], default='dong', max_length=20, verbose_name='Đơn vị')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='benefits/attachments/', verbose_name='Đính kèm quyết định')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngưng hoạt động')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('created_by_name', models.CharField(blank=True, max_length=200, verbose_name='Người tạo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BenefitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='Người thực hiện')),
                ('action', models.CharField(max_length=300, verbose_name='Hành động')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Tên trường')),
                ('old_value', models.TextField(blank=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, verbose_name='Giá trị mới')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.benefit', verbose_name='Phúc lợi')),
            ],
            options={
                'verbose_name': 'BenefitHistory',
                'verbose_name_plural': 'BenefitHistories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
