# Generated by Django 6.0.3 on 2026-05-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_benefit_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Tên chính sách phúc lợi'),
        ),
    ]
