# Generated by Django 6.0.3 on 2026-05-01 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_benefit_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Ma bang luong')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Ten bang luong')),
                ('period', models.CharField(max_length=7, verbose_name='Ky tinh luong')),
                ('scope', models.CharField(choices=[('all', 'Tat ca nhan vien'), ('selected', 'Tuy chon')], default='selected', max_length=20, verbose_name='Pham vi ap dung')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chu')),
                ('status', models.CharField(choices=[('draft', 'Luu nhap'), ('paying', 'Dang thanh toan'), ('paid', 'Da thanh toan'), ('cancelled', 'Da huy')], default='draft', max_length=20, verbose_name='Trang thai')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tong luong')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Da tra')),
                ('created_by_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi tao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='Nguoi thuc hien')),
                ('action', models.CharField(max_length=300, verbose_name='Hanh dong')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Ten truong')),
                ('old_value', models.TextField(blank=True, verbose_name='Gia tri cu')),
                ('new_value', models.TextField(blank=True, verbose_name='Gia tri moi')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.payroll', verbose_name='Bang luong')),
            ],
            options={
                'verbose_name': 'PayrollHistory',
                'verbose_name_plural': 'PayrollHistories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Luong co ban')),
                ('work_days', models.IntegerField(default=26, verbose_name='Ngay cong')),
                ('bonus_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Thuong')),
                ('benefit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phuc loi')),
                ('net_salary', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Luong thuc nhan')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chua thanh toan'), ('paid', 'Da thanh toan')], default='unpaid', max_length=20, verbose_name='Trang thai thanh toan')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='api.employee', verbose_name='Nhan vien')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_entries', to='api.payroll', verbose_name='Bang luong')),
            ],
            options={
                'verbose_name': 'PayrollEmployee',
                'verbose_name_plural': 'PayrollEmployees',
                'ordering': ['id'],
                'unique_together': {('payroll', 'employee')},
            },
        ),
    ]
