# Generated by Django 6.0.3 on 2026-05-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_bootstrap_state_and_production_defaults'),
        ('api', '0029_add_schedule_attendance_models'),
    ]

    operations = [
    ]
