# Generated by Django 6.0.3 on 2026-05-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_purchase_order_extra_fee_fields'),
        ('api', '0030_merge_20260501_1602'),
    ]

    operations = [
    ]
