# Generated by Django 6.0.3 on 2026-05-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20260505_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã yêu cầu đặt hàng')),
                ('name', models.CharField(max_length=200, verbose_name='Tên yêu cầu đặt hàng')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Ngày yêu cầu')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày mong muốn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Request',
                'verbose_name_plural': 'Order Requests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã phiếu nghiệm thu')),
                ('name', models.CharField(max_length=200, verbose_name='Tên phiếu nghiệm thu')),
                ('accepted_date', models.DateField(blank=True, null=True, verbose_name='Ngày nghiệm thu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('accepted', 'Đã nghiệm thu'), ('rejected', 'Từ chối')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Acceptance',
                'verbose_name_plural': 'Production Acceptances',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='productionrequestitem',
            name='production_request',
        ),
        migrations.RemoveField(
            model_name='productionrequestitem',
            name='semi_finished_product',
        ),
        migrations.AlterField(
            model_name='productbom',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bom_items', to='api.material', verbose_name='Nguyên vật liệu'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Tien can tra NCC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_plans', to='api.orderrequest', verbose_name='Yêu cầu đặt hàng'),
        ),
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú dòng')),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.orderrequest', verbose_name='Yêu cầu đặt hàng')),
                ('semi_finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items', to='api.semifinishedproduct', verbose_name='Bán thành phẩm')),
            ],
            options={
                'verbose_name': 'Order Request Item',
                'verbose_name_plural': 'Order Request Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAcceptanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng kế hoạch')),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng nghiệm thu')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú dòng')),
                ('production_acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.productionacceptance', verbose_name='Phiếu nghiệm thu')),
                ('semi_finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_acceptance_items', to='api.semifinishedproduct', verbose_name='Bán thành phẩm')),
            ],
            options={
                'verbose_name': 'Production Acceptance Item',
                'verbose_name_plural': 'Production Acceptance Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã lệnh sản xuất')),
                ('name', models.CharField(max_length=200, verbose_name='Tên lệnh sản xuất')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Lưu nháp'), ('in_progress', 'Đang sản xuất'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='api.orderrequest', verbose_name='Yêu cầu đặt hàng')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='api.productionplan', verbose_name='Kế hoạch sản xuất')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='productionacceptance',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptances', to='api.productionorder', verbose_name='Lệnh sản xuất'),
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng kế hoạch')),
                ('completed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Số lượng hoàn thành')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Thời lượng (phút)')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú dòng')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.productionorder', verbose_name='Lệnh sản xuất')),
                ('semi_finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_items', to='api.semifinishedproduct', verbose_name='Bán thành phẩm')),
            ],
            options={
                'verbose_name': 'Production Order Item',
                'verbose_name_plural': 'Production Order Items',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionRequest',
        ),
        migrations.DeleteModel(
            name='ProductionRequestItem',
        ),
    ]
